_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.11
            "6": 4.46.3
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": darwin-x86_64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
